[
  {
    col: 0,
    condition: [],
    default_values: "",
    description: "",
    fieldtype: "date",
    id: 4416,
    itemtype: "PluginGenericobjectSacisleme",
    links: [[Object]],
    name: "Tarih",
    plugin_formcreator_sections_id: 448,
    question_filled_value: "",
    required: 1,
    row: 0,
    show_empty: 0,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762db8fbcb6.22299911",
    values: '{"entity_restrict":"2"}',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: "[684]",
    description: "",
    fieldtype: "actor",
    id: 4417,
    itemtype: "PluginGenericobjectSacisleme",
    links: [[Object]],
    name: "Sorumlu",
    plugin_formcreator_sections_id: 448,
    question_filled_value: "",
    required: 1,
    row: 1,
    show_empty: 0,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762db9012f7.93791693",
    values: '{"entity_restrict":"2"}',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: "2",
    description: "",
    fieldtype: "glpiselect",
    id: 4415,
    itemtype: "PluginGenericobjectMakine",
    links: [[Object]],
    name: "Makine Adı",
    plugin_formcreator_sections_id: 448,
    question_filled_value: "",
    required: 1,
    row: 2,
    show_empty: 0,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762db89ec37.19280105",
    values: '{"entity_restrict":"2"}',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4418,
    itemtype: "",
    links: [[Object]],
    name: "1 - Sistemin detaylı yağ kaçağı kontrolü.",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 0,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762db90b482.67951179",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4430,
    itemtype: "",
    links: [[Object]],
    name: "Sonuç1",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 1,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762db9cdd04.14486444",
    values: '["Problem Yok","Problem Var"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Lütfen problemi yazınız.&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4431,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama1Sonuç",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 2,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762db9d8797.28129095",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Neden yapılmadığını açıklayın&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4424,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama1",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 3,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762db9280e1.99548972",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4419,
    itemtype: "",
    links: [[Object]],
    name: "2 - Otomatik valflerin fonskiyon kontrolü",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 4,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762db90fea0.08585216",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4432,
    itemtype: "",
    links: [[Object]],
    name: "Sonuç2",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 5,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762db9f0112.95243027",
    values: '["Problem Yok","Problem Var"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Lütfen problemi yazınız.&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4437,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama2Sonuç",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 6,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dba24c19.90150592",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Neden yapılmadığını açıklayın&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4425,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama2",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 7,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762db958497.98425427",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4420,
    itemtype: "",
    links: [[Object]],
    name: "3 - Akış şalteri fonksiyon kontrolü",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 8,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762db914ad6.64496725",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4433,
    itemtype: "",
    links: [[Object]],
    name: "Sonuç3",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 9,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762db9fafc7.27722849",
    values: '["Problem Yok","Problem Var"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Lütfen problemi yazınız.&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4438,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama3Sonuç",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 10,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dba3c877.84823118",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Neden yapılmadığını açıklayın&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4426,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama3",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 11,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762db96e592.02452589",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4421,
    itemtype: "",
    links: [[Object]],
    name: "4 - Köpük sensörü fonksiyon kontrolü",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 12,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762db91a432.60817729",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4434,
    itemtype: "",
    links: [[Object]],
    name: "Sonuç4",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 13,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dba05433.39411546",
    values: '["Problem Yok","Problem Var"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Lütfen problemi yazınız.&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4439,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama4Sonuç",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 14,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbab3745.70394207",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Neden yapılmadığını açıklayın&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4427,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama4",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 15,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762db983258.63128287",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4422,
    itemtype: "",
    links: [[Object]],
    name: "5 - Besleme pompası sızdırmazlık, ses ve dahili güvenlik valfi kontrolü",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 16,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762db91efc8.88495956",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4435,
    itemtype: "",
    links: [[Object]],
    name: "Sonuç5",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 17,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dba0f3c5.29303496",
    values: '["Problem Yok","Problem Var"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Lütfen problemi yazınız.&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4440,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama5Sonuç",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 18,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbad6ad4.39840819",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Neden yapılmadığını açıklayın&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4428,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama5",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 19,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762db99c1c6.45704916",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4423,
    itemtype: "",
    links: [[Object]],
    name: "6 - Yağ filtresi kontrolü",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 20,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762db923798.55391706",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4436,
    itemtype: "",
    links: [[Object]],
    name: "Sonuç6",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 21,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dba19ca2.26553915",
    values: '["Problem Yok","Problem Var"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Lütfen problemi yazınız.&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4441,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama6Sonuç",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 22,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbaecbd3.72683999",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Neden yapılmadığını açıklayın&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4429,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama6",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 23,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762db9b3639.83940945",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4442,
    itemtype: "",
    links: [[Object]],
    name: "7 - Basınç şalteri fonksiyon ve bağlantı noktası kontrolü",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 24,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762dbaffae8.42776778",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4446,
    itemtype: "",
    links: [[Object]],
    name: "Sonuç7",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 25,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbb17c75.53610342",
    values: '["Problem Yok","Problem Var"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Lütfen problemi yazınız.&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4454,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama7Sonuç",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 26,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbba51e1.46410155",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Neden yapılmadığını açıklayın&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4450,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama7",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 27,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbb400c4.86353471",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4443,
    itemtype: "",
    links: [[Object]],
    name: "8 - Tek yön akış valfi sızdırmazlık kontrolü ve ince filtre elemanları fiziksel durum kontrolü",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 28,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762dbb07017.77152531",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4447,
    itemtype: "",
    links: [[Object]],
    name: "Sonuç8",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 29,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbb21bd4.42520466",
    values: '["Problem Yok","Problem Var"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Lütfen problemi yazınız.&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4455,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama8Sonuç",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 30,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbbbe7d0.99713205",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Neden yapılmadığını açıklayın&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4451,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama8",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 31,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbb54ba6.77685155",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4444,
    itemtype: "",
    links: [[Object]],
    name: "9 - Kumanda panosu iç bağlantı kontrolü",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 32,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762dbb0cb51.93460238",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4448,
    itemtype: "",
    links: [[Object]],
    name: "Sonuç9",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 33,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbb2d5f5.05044055",
    values: '["Problem Yok","Problem Var"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Lütfen problemi yazınız.&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4456,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama9Sonuç",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 34,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbbd84c8.20783796",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Neden yapılmadığını açıklayın&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4452,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama9",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 35,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbb6fd89.15799409",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4445,
    itemtype: "",
    links: [[Object]],
    name: "10 - Topraklama kontrolü",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 36,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762dbb12ea4.21244284",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4449,
    itemtype: "",
    links: [[Object]],
    name: "Sonuç10",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 37,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbb36ba3.74876697",
    values: '["Problem Yok","Problem Var"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Lütfen problemi yazınız.&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4457,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama10Sonuç",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 38,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbbf75c6.85138069",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Neden yapılmadığını açıklayın&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4453,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama10",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 39,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbb8b869.07501680",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4458,
    itemtype: "",
    links: [[Object]],
    name: "11 - Vakum pompalarının filtrelerinin temizliği/değişimi",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 40,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762dbc14406.50918830",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4462,
    itemtype: "",
    links: [[Object]],
    name: "Sonuç11",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 41,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbc2a111.35193742",
    values: '["Problem Yok","Problem Var"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Lütfen problemi yazınız.&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4466,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama11Sonuç",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 42,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbc55176.21543881",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Neden yapılmadığını açıklayın&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4470,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama11",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 43,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbcc8a98.70840656",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4459,
    itemtype: "",
    links: [[Object]],
    name: "12 - Merkez sistemin yağ filtresinin değişimi",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 44,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762dbc19f50.96886416",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4463,
    itemtype: "",
    links: [[Object]],
    name: "Sonuç12",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 45,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbc35de8.41312476",
    values: '["Problem Yok","Problem Var"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Lütfen problemi yazınız.&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4467,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama12Sonuç",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 46,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbc6f537.06867940",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Neden yapılmadığını açıklayın&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4471,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama12",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 47,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbce3cb9.10052015",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4460,
    itemtype: "",
    links: [[Object]],
    name: "13 - Vakum testi kaçak oranı hesaplaması",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 48,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762dbc1f576.98791208",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4464,
    itemtype: "",
    links: [[Object]],
    name: "Sonuç13",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 49,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbc408e1.72005226",
    values: '["Problem Yok","Problem Var"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Lütfen problemi yazınız.&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4468,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama13Sonuç",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 50,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbc885d1.31801557",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Neden yapılmadığını açıklayın&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4472,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama13",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 51,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbcf7206.60155451",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4461,
    itemtype: "",
    links: [[Object]],
    name: "14 - Isıtma ünitesi fonksiyon testi",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 52,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762dbc24a51.00145796",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4465,
    itemtype: "",
    links: [[Object]],
    name: "Sonuç14",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 53,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbc4b076.32215375",
    values: '["Problem Yok","Problem Var"]',
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Lütfen problemi yazınız.&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4469,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama14Sonuç",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 54,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbca0257.82253316",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [[Object]],
    default_values: "",
    description: "&#60;p&#62;Neden yapılmadığını açıklayın&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4473,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama14",
    plugin_formcreator_sections_id: 449,
    question_filled_value: "",
    required: 1,
    row: 55,
    show_empty: 0,
    show_rule: 2,
    uuid: "7ebc9b73-8d9ac576-669762dbd197e5.16064145",
    values: null,
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "&#60;p&#62;Genel Açıklama&#60;/p&#62;",
    fieldtype: "textarea",
    id: 4474,
    itemtype: "",
    links: [[Object]],
    name: "Açıklama",
    plugin_formcreator_sections_id: 450,
    question_filled_value: "",
    required: 0,
    row: 0,
    show_empty: 0,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-669762dbd4a382.46042505",
    values: null,
    width: 4,
  },
];

[
  {
    col: 0,
    default_values: "0",
    description: "",
    fieldtype: "dropdown",
    id: 4655,
    itemtype: "Location",
    links: [[Object]],
    name: "Dropdown",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 1,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a353af371325.79849481",
    values:
      '{"show_tree_depth":"3","show_tree_root":"0","selectable_tree_root":"0","entity_restrict":"2"}',
    width: 4,
  },
  {
    col: 0,
    default_values: null,
    description: "",
    fieldtype: "file",
    id: 4656,
    itemtype: "",
    links: [[Object]],
    name: "File",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 2,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a353c0ebd3a0.47279717",
    values: null,
    width: 4,
  },
  {
    col: 0,
    default_values: null,
    description: "",
    fieldtype: "select",
    id: 4657,
    itemtype: "",
    links: [[Object]],
    name: "Select",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 3,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a353d888ee05.63402979",
    values: '["1","2","3"]',
    width: 4,
  },
  {
    col: 0,
    default_values: "",
    description: "",
    fieldtype: "multiselect",
    id: 4658,
    itemtype: "",
    links: [[Object]],
    name: "Multiselect",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 4,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a353fd4f7005.47859677",
    values: '["1","2","3","4","5"]',
    width: 4,
  },
  {
    col: 0,
    default_values: "",
    description: "",
    fieldtype: "float",
    id: 4659,
    itemtype: "",
    links: [[Object]],
    name: "Float",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 5,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a3543d1c3c79.90359044",
    values: "",
    width: 4,
  },
  {
    col: 0,
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4660,
    itemtype: "",
    links: [[Object]],
    name: "Radios",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 6,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a354789d66d0.13417298",
    values: '["Var","Yok","Nötr","Ve","veya"]',
    width: 4,
  },
  {
    col: 0,
    default_values: "5",
    description: "",
    fieldtype: "urgency",
    id: 4661,
    itemtype: "",
    links: [[Object]],
    name: "Urgency",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 7,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a354a5cdeb93.69646170",
    values: '["var","yok","ve","veya"]',
    width: 4,
  },
  {
    col: 0,
    default_values: "",
    description: "",
    fieldtype: "date",
    id: 4662,
    itemtype: "",
    links: [[Object]],
    name: "Date",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 0,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a3557a7492e4.01370493",
    values: null,
    width: 4,
  },
  {
    col: 0,
    default_values: "",
    description: "",
    fieldtype: "checkboxes",
    id: 4663,
    itemtype: "",
    links: [[Object]],
    name: "Soru8",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 8,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a355c81f2aa7.81800861",
    values: '["1","2","3","4","5"]',
    width: 4,
  },
  {
    col: 0,
    default_values: "[]",
    description: "",
    fieldtype: "actor",
    id: 4664,
    itemtype: "",
    links: [[Object]],
    name: "Soru9",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 9,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a3562e9624a2.16809685",
    values: null,
    width: 4,
  },
];

[
  {
    col: 0,
    default_values: "0",
    description: "",
    fieldtype: "dropdown",
    id: 4655,
    itemtype: "Location",
    links: [[Object]],
    name: "Dropdown",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 1,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a353af371325.79849481",
    values:
      '{"show_tree_depth":"3","show_tree_root":"0","selectable_tree_root":"0","entity_restrict":"2"}',
    width: 4,
  },
  {
    col: 0,
    default_values: null,
    description: "",
    fieldtype: "file",
    id: 4656,
    itemtype: "",
    links: [[Object]],
    name: "File",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 2,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a353c0ebd3a0.47279717",
    values: null,
    width: 4,
  },
  {
    col: 0,
    default_values: null,
    description: "",
    fieldtype: "select",
    id: 4657,
    itemtype: "",
    links: [[Object]],
    name: "Select",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 3,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a353d888ee05.63402979",
    values: '["1","2","3"]',
    width: 4,
  },
  {
    col: 0,
    default_values: "",
    description: "",
    fieldtype: "multiselect",
    id: 4658,
    itemtype: "",
    links: [[Object]],
    name: "Multiselect",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 4,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a353fd4f7005.47859677",
    values: '["1","2","3","4","5"]',
    width: 4,
  },
  {
    col: 0,
    default_values: "",
    description: "",
    fieldtype: "float",
    id: 4659,
    itemtype: "",
    links: [[Object]],
    name: "Float",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 5,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a3543d1c3c79.90359044",
    values: "",
    width: 4,
  },
  {
    col: 0,
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4660,
    itemtype: "",
    links: [[Object]],
    name: "Radios",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 6,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a354789d66d0.13417298",
    values: '["Var","Yok","Nötr","Ve","veya"]',
    width: 4,
  },
  {
    col: 0,
    default_values: "",
    description: "",
    fieldtype: "date",
    id: 4662,
    itemtype: "",
    links: [[Object]],
    name: "Date",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 0,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a3557a7492e4.01370493",
    values: null,
    width: 4,
  },
  {
    col: 0,
    default_values: "",
    description: "",
    fieldtype: "checkboxes",
    id: 4663,
    itemtype: "",
    links: [[Object]],
    name: "Soru8",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 7,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a355c81f2aa7.81800861",
    values: '["1","2","3","4","5"]',
    width: 4,
  },
  {
    col: 0,
    default_values: "[]",
    description: "",
    fieldtype: "actor",
    id: 4664,
    itemtype: "",
    links: [[Object]],
    name: "Soru9",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 8,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66a3562e9624a2.16809685",
    values: null,
    width: 4,
  },
  {
    col: 0,
    default_values: "5",
    description: "",
    fieldtype: "urgency",
    id: 4665,
    itemtype: "",
    links: [[Object]],
    name: "Urgency",
    plugin_formcreator_sections_id: 460,
    required: 0,
    row: 9,
    show_empty: 0,
    show_rule: 1,
    uuid: "1d36e7d3-8d9ac576-66b4bc5ecc3883.46363304",
    values: null,
    width: 4,
  },
];

[
  {
    ancestors_cache: "[]",
    comment: "",
    completename: "Makina Rutin Kontrol",
    id: 1,
    knowbaseitemcategories_id: 0,
    level: 1,
    name: "Makina Rutin Kontrol",
    plugin_formcreator_categories_id: 0,
    sons_cache: null,
  },
  {
    ancestors_cache: null,
    comment: "",
    completename: "MAKINE YILLIK KONTROL > OG > Sac İşleme > ABKANT MAKİNESİ",
    id: 3,
    knowbaseitemcategories_id: 0,
    level: 4,
    links: [[Object]],
    name: "ABKANT MAKİNESİ",
    plugin_formcreator_categories_id:
      "MAKINE YILLIK KONTROL &#62; OG &#62; Sac İşleme",
    sons_cache: '{"3":3}',
  },
  {
    ancestors_cache: '{"5":5,"6":6}',
    comment: "",
    completename: "MAKINE YILLIK KONTROL > OG > Sac İşleme",
    id: 4,
    knowbaseitemcategories_id: 0,
    level: 3,
    links: [[Object]],
    name: "Sac İşleme",
    plugin_formcreator_categories_id: "MAKINE YILLIK KONTROL &#62; OG",
    sons_cache: '{"4":4,"3":3}',
  },
  {
    ancestors_cache: "[]",
    comment: "",
    completename: "MAKINE YILLIK KONTROL",
    id: 5,
    knowbaseitemcategories_id: 0,
    level: 1,
    name: "MAKINE YILLIK KONTROL",
    plugin_formcreator_categories_id: 0,
    sons_cache: '{"5":5,"6":6,"4":4,"7":7,"9":9,"11":11,"12":12,"13":13,"3":3}',
  },
  {
    ancestors_cache: '{"5":5}',
    comment: "",
    completename: "MAKINE YILLIK KONTROL > OG",
    id: 6,
    knowbaseitemcategories_id: 0,
    level: 2,
    links: [[Object]],
    name: "OG",
    plugin_formcreator_categories_id: "MAKINE YILLIK KONTROL",
    sons_cache: '{"6":6,"13":13,"7":7,"12":12,"9":9,"11":11,"4":4,"3":3}',
  },
  {
    ancestors_cache: '{"5":5,"6":6}',
    comment: "",
    completename: "MAKINE YILLIK KONTROL > OG > Epoksi",
    id: 7,
    knowbaseitemcategories_id: 0,
    level: 3,
    links: [[Object]],
    name: "Epoksi",
    plugin_formcreator_categories_id: "MAKINE YILLIK KONTROL &#62; OG",
    sons_cache: '{"7":7}',
  },
  {
    ancestors_cache: '{"5":5,"6":6}',
    comment: "",
    completename: "MAKINE YILLIK KONTROL > OG > Kompenant",
    id: 9,
    knowbaseitemcategories_id: 0,
    level: 3,
    links: [[Object]],
    name: "Kompenant",
    plugin_formcreator_categories_id: "MAKINE YILLIK KONTROL &#62; OG",
    sons_cache: null,
  },
  {
    ancestors_cache: '{"5":5,"6":6}',
    comment: "",
    completename: "MAKINE YILLIK KONTROL > OG > Mekanik",
    id: 11,
    knowbaseitemcategories_id: 0,
    level: 3,
    links: [[Object]],
    name: "Mekanik",
    plugin_formcreator_categories_id: "MAKINE YILLIK KONTROL &#62; OG",
    sons_cache: '{"11":11}',
  },
  {
    ancestors_cache: '{"5":5,"6":6}',
    comment: "",
    completename: "MAKINE YILLIK KONTROL > OG > Hucre_Montaj",
    id: 12,
    knowbaseitemcategories_id: 0,
    level: 3,
    links: [[Object]],
    name: "Hucre_Montaj",
    plugin_formcreator_categories_id: "MAKINE YILLIK KONTROL &#62; OG",
    sons_cache: '{"12":12}',
  },
  {
    ancestors_cache: '{"5":5,"6":6}',
    comment: "",
    completename: "MAKINE YILLIK KONTROL > OG > Beton köşk",
    id: 13,
    knowbaseitemcategories_id: 0,
    level: 3,
    links: [[Object]],
    name: "Beton köşk",
    plugin_formcreator_categories_id: "MAKINE YILLIK KONTROL &#62; OG",
    sons_cache: null,
  },
  {
    ancestors_cache: '{"1":1}',
    comment: "",
    completename: "Makina Rutin Kontrol > Beton köşk",
    id: 14,
    knowbaseitemcategories_id: 0,
    level: 2,
    links: [[Object]],
    name: "Beton köşk",
    plugin_formcreator_categories_id: "Makina Rutin Kontrol",
    sons_cache: '{"14":14}',
  },
  {
    ancestors_cache: '{"1":1}',
    comment: "",
    completename: "Makina Rutin Kontrol > Epoksi",
    id: 15,
    knowbaseitemcategories_id: 0,
    level: 2,
    links: [[Object]],
    name: "Epoksi",
    plugin_formcreator_categories_id: "Makina Rutin Kontrol",
    sons_cache: '{"15":15}',
  },
  {
    ancestors_cache: '{"1":1}',
    comment: "",
    completename: "Makina Rutin Kontrol > Bakirhane",
    id: 16,
    knowbaseitemcategories_id: 0,
    level: 2,
    links: [[Object]],
    name: "Bakirhane",
    plugin_formcreator_categories_id: "Makina Rutin Kontrol",
    sons_cache: '{"16":16}',
  },
  {
    ancestors_cache: '{"1":1}',
    comment: "",
    completename: "Makina Rutin Kontrol > Sacisleme",
    id: 17,
    knowbaseitemcategories_id: 0,
    level: 2,
    links: [[Object]],
    name: "Sacisleme",
    plugin_formcreator_categories_id: "Makina Rutin Kontrol",
    sons_cache: '{"17":17}',
  },
  {
    ancestors_cache: '{"1":1}',
    comment: "",
    completename: "Makina Rutin Kontrol > OG-Mekanik",
    id: 18,
    knowbaseitemcategories_id: 0,
    level: 2,
    links: [[Object]],
    name: "OG-Mekanik",
    plugin_formcreator_categories_id: "Makina Rutin Kontrol",
    sons_cache: '{"18":18}',
  },
  {
    ancestors_cache: '{"1":1}',
    comment: "",
    completename: "Makina Rutin Kontrol > Hucre Montaj",
    id: 19,
    knowbaseitemcategories_id: 0,
    level: 2,
    links: [[Object]],
    name: "Hucre Montaj",
    plugin_formcreator_categories_id: "Makina Rutin Kontrol",
    sons_cache: null,
  },
  {
    ancestors_cache: '{"1":1}',
    comment: "",
    completename: "Makina Rutin Kontrol > GucSarim",
    id: 20,
    knowbaseitemcategories_id: 0,
    level: 2,
    links: [[Object]],
    name: "GucSarim",
    plugin_formcreator_categories_id: "Makina Rutin Kontrol",
    sons_cache: '{"20":20}',
  },
  {
    ancestors_cache: '{"1":1}',
    comment: "",
    completename: "Makina Rutin Kontrol > GucCekirdek",
    id: 21,
    knowbaseitemcategories_id: 0,
    level: 2,
    links: [[Object]],
    name: "GucCekirdek",
    plugin_formcreator_categories_id: "Makina Rutin Kontrol",
    sons_cache: null,
  },
  {
    ancestors_cache: '{"1":1}',
    comment: "",
    completename: "Makina Rutin Kontrol > GucSonMontaj",
    id: 22,
    knowbaseitemcategories_id: 0,
    level: 2,
    links: [[Object]],
    name: "GucSonMontaj",
    plugin_formcreator_categories_id: "Makina Rutin Kontrol",
    sons_cache: null,
  },
  {
    ancestors_cache: '{"1":1}',
    comment: "",
    completename: "Makina Rutin Kontrol > GucFirinlar",
    id: 23,
    knowbaseitemcategories_id: 0,
    level: 2,
    links: [[Object]],
    name: "GucFirinlar",
    plugin_formcreator_categories_id: "Makina Rutin Kontrol",
    sons_cache: null,
  },
  {
    ancestors_cache: '{"1":1}',
    comment: "",
    completename: "Makina Rutin Kontrol > DagitimSarim",
    id: 24,
    knowbaseitemcategories_id: 0,
    level: 2,
    links: [[Object]],
    name: "DagitimSarim",
    plugin_formcreator_categories_id: "Makina Rutin Kontrol",
    sons_cache: '{"24":24}',
  },
  {
    ancestors_cache: "[]",
    comment: "",
    completename: "DENEME",
    id: 25,
    knowbaseitemcategories_id: 0,
    level: 1,
    name: "DENEME",
    plugin_formcreator_categories_id: 0,
    sons_cache: '{"25":25}',
  },
];

[
  {
    comment: "",
    date_creation: "2024-07-17 12:23:08",
    date_mod: "2024-08-09 13:41:58",
    entities_id: 0,
    groups_id: 139,
    id: 1,
    is_deleted: 0,
    is_helpdesk_visible: 1,
    is_recursive: 0,
    is_template: 0,
    links: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    locations_id: 37,
    manufacturers_id: 35,
    name: "Makine - 1",
    notepad: null,
    otherserial: "34545",
    serial: "AS23234",
    states_id: 2,
    template_name: "",
    users_id: 659,
    users_id_tech: 684,
  },
  {
    comment: "",
    date_creation: "2024-07-17 12:23:25",
    date_mod: "2024-08-07 10:12:39",
    entities_id: 0,
    groups_id: 139,
    id: 2,
    is_deleted: 0,
    is_helpdesk_visible: 1,
    is_recursive: 0,
    is_template: 0,
    links: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    locations_id: 37,
    manufacturers_id: 35,
    name: "Makine - 4",
    notepad: null,
    otherserial: "34545",
    serial: "AS23234",
    states_id: 2,
    template_name: "",
    users_id: 659,
    users_id_tech: 684,
  },
  {
    comment: "",
    date_creation: "2024-07-17 12:23:25",
    date_mod: "2024-08-07 10:05:39",
    entities_id: 0,
    groups_id: 139,
    id: 3,
    is_deleted: 0,
    is_helpdesk_visible: 1,
    is_recursive: 0,
    is_template: 0,
    links: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    locations_id: 37,
    manufacturers_id: 42,
    name: "Makine - 2",
    notepad: null,
    otherserial: "435435",
    serial: "DF-2343",
    states_id: 2,
    template_name: "",
    users_id: 659,
    users_id_tech: 684,
  },
  {
    comment: "",
    date_creation: "2024-07-17 12:23:25",
    date_mod: "2024-07-18 17:06:41",
    entities_id: 0,
    groups_id: 139,
    id: 4,
    is_deleted: 0,
    is_helpdesk_visible: 1,
    is_recursive: 0,
    is_template: 0,
    links: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    locations_id: 37,
    manufacturers_id: 12,
    name: "Makine - 3",
    notepad: null,
    otherserial: "3456436",
    serial: "TG34543543",
    states_id: 2,
    template_name: "",
    users_id: 659,
    users_id_tech: 684,
  },
  {
    comment: "",
    date_creation: "2024-07-17 12:24:55",
    date_mod: "2024-08-09 13:42:18",
    entities_id: 0,
    groups_id: 139,
    id: 5,
    is_deleted: 0,
    is_helpdesk_visible: 1,
    is_recursive: 0,
    is_template: 0,
    links: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    locations_id: 37,
    manufacturers_id: 52,
    name: "Makine - 6",
    notepad: null,
    otherserial: "867456",
    serial: "3456436",
    states_id: 2,
    template_name: "",
    users_id: 684,
    users_id_tech: 684,
  },
  {
    comment: "",
    date_creation: "2024-07-17 12:24:55",
    date_mod: "2024-08-07 10:12:20",
    entities_id: 0,
    groups_id: 139,
    id: 6,
    is_deleted: 0,
    is_helpdesk_visible: 1,
    is_recursive: 0,
    is_template: 0,
    links: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    locations_id: 37,
    manufacturers_id: 35,
    name: "Makine - 5",
    notepad: null,
    otherserial: "76864",
    serial: "TG546546",
    states_id: 2,
    template_name: "",
    users_id: 659,
    users_id_tech: 684,
  },
];

[
  {
    col: 0,
    condition: [],
    default_values: "",
    description: "",
    fieldtype: "date",
    id: 4476,
    itemtype: "PluginGenericobjectSacisleme",
    links: [[Object]],
    name: "Tarih",
    plugin_formcreator_sections_id: 451,
    question_filled_value: "",
    required: 1,
    row: 0,
    show_empty: 0,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-66978e28320511.67966455",
    values: '{"entity_restrict":"2"}',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: "[659]",
    description: "",
    fieldtype: "actor",
    id: 4477,
    itemtype: "PluginGenericobjectSacisleme",
    links: [[Object]],
    name: "Sorumlu",
    plugin_formcreator_sections_id: 451,
    question_filled_value: "",
    required: 1,
    row: 1,
    show_empty: 0,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-66978e28324316.28710129",
    values: '{"entity_restrict":"2"}',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: "1",
    description: "",
    fieldtype: "glpiselect",
    id: 4475,
    itemtype: "PluginGenericobjectMakine",
    links: [[Object]],
    name: "Makine Adı",
    plugin_formcreator_sections_id: 451,
    question_filled_value: "",
    required: 1,
    row: 2,
    show_empty: 0,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-66978e283197e9.77303583",
    values: '{"entity_restrict":"2"}',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4478,
    itemtype: "",
    links: [[Object]],
    name: "1 - Sistemin detaylı yağ kaçağı kontrolü.",
    plugin_formcreator_sections_id: 452,
    question_filled_value: "",
    required: 1,
    row: 0,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-66978e2832c904.50321458",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4479,
    itemtype: "",
    links: [[Object]],
    name: "2 - Otomatik valflerin fonskiyon kontrolü",
    plugin_formcreator_sections_id: 452,
    question_filled_value: "",
    required: 1,
    row: 4,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-66978e283307a6.49893853",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4480,
    itemtype: "",
    links: [[Object]],
    name: "3 - Akış şalteri fonksiyon kontrolü",
    plugin_formcreator_sections_id: 452,
    question_filled_value: "",
    required: 1,
    row: 8,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-66978e28334199.15399216",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4481,
    itemtype: "",
    links: [[Object]],
    name: "4 - Köpük sensörü fonksiyon kontrolü",
    plugin_formcreator_sections_id: 452,
    question_filled_value: "",
    required: 1,
    row: 12,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-66978e28337da5.55227767",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4482,
    itemtype: "",
    links: [[Object]],
    name: "5 - Besleme pompası sızdırmazlık, ses ve dahili güvenlik valfi kontrolü",
    plugin_formcreator_sections_id: 452,
    question_filled_value: "",
    required: 1,
    row: 16,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-66978e2833b722.18754511",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4483,
    itemtype: "",
    links: [[Object]],
    name: "6 - Yağ filtresi kontrolü",
    plugin_formcreator_sections_id: 452,
    question_filled_value: "",
    required: 1,
    row: 20,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-66978e2833f035.67250445",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4502,
    itemtype: "",
    links: [[Object]],
    name: "7 - Basınç şalteri fonksiyon ve bağlantı noktası kontrolü",
    plugin_formcreator_sections_id: 452,
    question_filled_value: "",
    required: 1,
    row: 24,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-66978e284417b3.07701115",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4503,
    itemtype: "",
    links: [[Object]],
    name: "8 - Tek yön akış valfi sızdırmazlık kontrolü ve ince filtre elemanları fiziksel durum kontrolü",
    plugin_formcreator_sections_id: 452,
    question_filled_value: "",
    required: 1,
    row: 28,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-66978e28445153.12578952",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4504,
    itemtype: "",
    links: [[Object]],
    name: "9 - Kumanda panosu iç bağlantı kontrolü",
    plugin_formcreator_sections_id: 452,
    question_filled_value: "",
    required: 1,
    row: 32,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-66978e28448f98.53699534",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4505,
    itemtype: "",
    links: [[Object]],
    name: "10 - Topraklama kontrolü",
    plugin_formcreator_sections_id: 452,
    question_filled_value: "",
    required: 1,
    row: 36,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-66978e2844d2f0.66043624",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4518,
    itemtype: "",
    links: [[Object]],
    name: "11 - Vakum pompalarının filtrelerinin temizliği/değişimi",
    plugin_formcreator_sections_id: 452,
    question_filled_value: "",
    required: 1,
    row: 40,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-66978e2853a0e3.63748141",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4519,
    itemtype: "",
    links: [[Object]],
    name: "12 - Merkez sistemin yağ filtresinin değişimi",
    plugin_formcreator_sections_id: 452,
    question_filled_value: "",
    required: 1,
    row: 44,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-66978e2853ee82.15863106",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4520,
    itemtype: "",
    links: [[Object]],
    name: "13 - Vakum testi kaçak oranı hesaplaması",
    plugin_formcreator_sections_id: 452,
    question_filled_value: "",
    required: 1,
    row: 48,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-66978e28543b49.04661102",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
  {
    col: 0,
    condition: [],
    default_values: null,
    description: "",
    fieldtype: "radios",
    id: 4521,
    itemtype: "",
    links: [[Object]],
    name: "14 - Isıtma ünitesi fonksiyon testi",
    plugin_formcreator_sections_id: 452,
    question_filled_value: "",
    required: 1,
    row: 52,
    show_empty: 1,
    show_rule: 1,
    uuid: "7ebc9b73-8d9ac576-66978e2854fab7.69613367",
    values: '["Yapıldı","Yapılmadı"]',
    width: 4,
  },
];
